### ISSUE TITLE
default group

### ISSUE THREAD

**Issue by lonnen** [mozilla/corsica#19]
Richard was asking after a way of easily defining a default group. `*` isn't exactly right because that would impact all TVs. We're after a way to have new screens that are not otherwise defined in a group to get some content.

**Comment by RAMilewski** [comment]
How about just a tag called "Unsubscribed"   That could even present web pages with <gasp!> documentation about how it works...  and suggestions for how to use it!

**Comment by RAMilewski** [comment]
Potch pushed a change so that content in the "default" tag is displayed on unconfigured client screens.

**Comment by potch** [comment]
It can!
