### ISSUE TITLE
Implement weighting for content

### ISSUE THREAD

**Issue by fwenzel** [mozilla/corsica#22]
From Yammer. It'd be great to be able to show one thing more/less frequently than another. This might take the shape of likelihoods (i.e., random next row and the chance that one is picked over the other varies), or time (a lower priority screen is shown for shorter time frames).

@mythmon writes:
"Right now there is no way to lower the weight of particular rows. We have a hacky way to raise priority of things by duplicating rows, but it's pretty rough. Shortly after this poll was posted, I doubled the probability of the "martell" command row, which shows logos from http://blog.seanmartell.com/brands/

Better random weighting is something we'd like to implement in the near future though."

**Comment by lonnen** [comment]
wontfixing this for now. It's already difficult to reason about the content subscriptions. Open to revisiting this later.
