### ISSUE TITLE
Add option to redirect HTTP to HTTPS and send HSTS header

### ISSUE THREAD

**Issue by edmorley** [mozilla/corsica#51]
This could be achieved using something like:
https://github.com/helmetjs/helmet

This is required so that the Mozilla instance can send HSTS headers for:
https://bugzilla.mozilla.org/show_bug.cgi?id=1137035

**Comment by potch** [comment]
The issue we have is with how corsica works- many entries in the playlist are HTTP, and won't even load when the server is loaded over HTTPS. I don't know how to say to an iframe, "hey it's cool mixed content is fine here", so I don't even think corsica is usable on HTTPS
